# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pillarnext_explained',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/pillarnext_explained',
                'lib_path': 'pillarnext_explained'},
  'syms': {}}
