name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          pip install 'numpy<2'
          pip install torch torchvision
      - name: Deploy with Quarto
        uses: fastai/workflows/quarto-ghp@master
        with:
          version: '3.10'