name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          pip install 'numpy<2'
          pip install torch torchvision
      - name: Run nbdev-ci
        uses: fastai/workflows/nbdev-ci@master